export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const DISMISS_LOGIN_ERROR = 'DISMISS_LOGIN_ERROR';

export const REQUEST_STARTED = 'REQUEST_STARTED';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const REQUEST_ADD_PRODUCT_SUCCEDED = 'REQUEST_ADD_PRODUCT_SUCCEDED';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
